const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),vendor=process.env.LEAFLET_TEST_DIR||path.join(root,'..','map-test-vendor');
const html=fs.readFileSync(path.join(root,'s3r86w8a.html'),'utf8');
const adapter=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].find(m=>m[1].includes("var KEY='arap-jiphap-map-v1'"))[1];
const server=http.createServer((req,res)=>{const n=req.url.split('?')[0];res.setHeader('Content-Type',n.endsWith('.css')?'text/css':n.endsWith('.js')?'text/javascript':'text/html; charset=utf-8');
if(n==='/')return res.end('<link rel="stylesheet" href="/leaflet.css"><script src="/leaflet.js"></script><div id="mapBox" style="height:650px;width:900px"></div><div id="mapBox-m" style="height:650px;width:900px"></div><script src="/arap_jiphap_parcels.js"></script><script src="/arap_map.js"></script><script>'+adapter+'</script>');
const f=path.join(n.startsWith('/leaflet.')?vendor:root,n.slice(1));if(!fs.existsSync(f)){res.statusCode=404;return res.end();}res.end(fs.readFileSync(f));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL});try{
const page=await browser.newPage({viewport:{width:1000,height:750}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());
await page.addInitScript(()=>{const store={};for(let i=0;i<2;i++){const x=126.91+i*.001,y=37.53,addr='서울특별시 영등포구 당산동6가 '+(i?'280-9':'280-1');store[addr]={_xy:{x:x+.0005,y:y+.0005,addr,q:addr,geom:{type:'Polygon',coordinates:[[[x,y],[x+.001,y],[x+.001,y+.001],[x,y+.001],[x,y]]]}}};}localStorage.setItem('arap-jiphap-map-v1',JSON.stringify(store));});
await page.goto(base);await page.evaluate(()=>{const orig=L.map;window.maps={};L.map=function(id,opts){return maps[id]=orig(id,opts);};});
for(const sfx of ['','-m']){const id='mapBox'+sfx;await page.evaluate(sfx=>ArapJiphapMap.show(sfx,{jibun:'서울특별시 영등포구 당산동6가 280-1, 280-9'}),sfx);await page.locator('#'+id+' .lab').waitFor();
assert.equal(await page.locator('#'+id+' .lab').count(),1);assert.equal(await page.locator('#'+id+' .lab').textContent(),'[본건]');assert.equal(await page.locator('#'+id+' path.leaflet-interactive').count(),2);
const check=()=>page.evaluate(id=>{const map=maps[id],el=document.getElementById(id),marker=el.querySelector('.leaflet-marker-icon'),svg=marker.querySelector('svg'),tip=svg.querySelector('polygon').getAttribute('points').split(' ')[0].split(',').map(Number);const origin=L.DomUtil.getPosition(marker),p=L.point(origin.x+tip[0]-210,origin.y+tip[1]-210);const nw=map.latLngToLayerPoint([37.531,126.91]),se=map.latLngToLayerPoint([37.53,126.912]);const onOuter=Math.min(Math.abs(p.x-nw.x),Math.abs(p.x-se.x),Math.abs(p.y-nw.y),Math.abs(p.y-se.y))<1;return {onOuter,p:{x:p.x,y:p.y},nw:{x:nw.x,y:nw.y},se:{x:se.x,y:se.y}};},id);
assert.ok((await check()).onOuter,JSON.stringify(await check()));await page.evaluate(id=>maps[id].setZoom(17,{animate:false}),id);assert.ok((await check()).onOuter);
const lab=page.locator('#'+id+' .lab');await lab.scrollIntoViewIfNeeded();const b=await lab.boundingBox();await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+80,b.y+b.height/2+50,{steps:6});await page.mouse.up();assert.ok((await check()).onOuter,JSON.stringify(await check()));assert.ok(await page.evaluate(()=>Object.values(JSON.parse(localStorage.getItem('arap-jiphap-map-v1'))).some(o=>o._xy.labOff)));console.log('PASS',sfx||'single','two boundaries, one subject label, edge tip before/after zoom and drag');}
await page.evaluate(()=>ArapJiphapMap.show('',{jibun:'서울특별시 영등포구 당산동6가 280-1'}));await page.waitForFunction(()=>document.querySelectorAll('#mapBox path.leaflet-interactive').length===1);assert.equal(await page.locator('#mapBox .lab').textContent(),'[본건]');
await page.evaluate(()=>{const store=JSON.parse(localStorage.getItem('arap-jiphap-map-v1'));return ArapJiphapMap.view('').open(Object.keys(store).map((loc,i)=>({o:store[loc],loc,kind:'본건',label:'기존 '+i,color:'#dc2626',poly:true,pick:true})));});assert.equal(await page.locator('#mapBox .lab').count(),2);console.log('PASS one-parcel subject and default ungrouped map compatibility');
await page.locator('#mapBox').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(root,'..','map-test-vendor','grouped.png')});assert.deepEqual(errors,[]);
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
