const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..');
const api='{buildSjIdxText,detectSjKind,assembleToice,buildGeonmyeong,buildCheongguTokenMap,buildTokenHwpx,V2CHEONGGU_TPL_B64,V2CHEONGGU_BLUE2BLACK,parseZip,generateDocxBlob,DEFAULT_TPL_RES:typeof DEFAULT_TPL_RES!=="undefined"?DEFAULT_TPL_RES:null,DEFAULT_TPL_COM:typeof DEFAULT_TPL_COM!=="undefined"?DEFAULT_TPL_COM:null}';
const server=http.createServer((req,res)=>{const f=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(!f.startsWith(root)||!fs.existsSync(f)){res.statusCode=404;return res.end();}let s=fs.readFileSync(f);if(f.endsWith('s3r86w8a.html'))s=s.toString().replace("ReactDOM.createRoot(document.getElementById('root'))",`window.testSingle=${api};ReactDOM.createRoot(document.getElementById('root'))`).replace("ReactDOM.createRoot(document.getElementById('root-multi'))",`window.testMulti=${api};ReactDOM.createRoot(document.getElementById('root-multi'))`);res.setHeader('Content-Type',f.endsWith('.html')?'text/html; charset=utf-8':'text/javascript');res.end(s);});
const addr='서울특별시 영등포구 당산동6가 280-1, 280-9';
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL});
try{for(const mode of ['single','multi']){const ctx=await browser.newContext(),page=await ctx.newPage(),errors=[];page.setDefaultTimeout(20000);console.log('START',mode);page.on('console',m=>{if(m.text().startsWith('TEST'))console.log(m.text());});page.on('pageerror',e=>{errors.push(e.message);console.error(e.message);});page.on('dialog',d=>d.accept());
await ctx.route('**/*',r=>{const u=r.request().url();if(u.includes('arap_access.js'))return r.fulfill({body:'',contentType:'text/javascript'});if(u.startsWith(base))return r.continue();return r.abort();});
await page.addInitScript(({mode,addr})=>{localStorage.setItem('arap-user-name','wdw');localStorage.setItem('arap-jiphap-mode',mode);const pre=mode==='multi'?'v2:':'';if(localStorage.getItem(pre+'case:PARITY'))return;localStorage.setItem(pre+'appraisal-case-list',JSON.stringify([{id:'PARITY',label:'합성 검증'}]));localStorage.setItem(pre+'case:PARITY',JSON.stringify({ov:{caseNo:'PARITY',client:'검증',jibun:addr,buildingName:'검증건물',baseDate:'2026.09.21',kind:'오피스텔',units:[{id:1,dong:'102',floor:'3',ho:'304',area:'30'},{id:2,dong:'102',floor:'7',ho:'704',area:'30'}]},cases:[{id:'office-case',symbol:1,isShown:true,isSelected:false,location:'서울특별시 영등포구',aptName:'검증 오피스텔',tradeDate:'2026.02.10',exclusiveArea:30,unitPrice:5000000}],precs:[],propType:'주거용'}));},{mode,addr});
await page.goto(base+'/s3r86w8a.html');const scope=page.locator(mode==='single'?'#root':'#root-multi');await scope.getByText('② 대상물건개요',{exact:true}).click({timeout:60000});
const inputs=scope.locator('textarea[placeholder="토지이음에서 복사한 지역·지구 내용 붙여넣기"]');assert.equal(await inputs.count(),2);await inputs.nth(0).fill('준공업지역');await inputs.nth(1).fill('도시지역, 도로(접합)');
const key=(mode==='multi'?'v2:':'')+'case:PARITY';await page.waitForFunction(k=>JSON.parse(localStorage.getItem(k)).ov.toiceRaw?.['280-9']==='도시지역, 도로(접합)',key);
await page.reload();await scope.getByText('② 대상물건개요',{exact:true}).click();assert.equal(await inputs.nth(0).inputValue(),'준공업지역');assert.equal(await inputs.nth(1).inputValue(),'도시지역, 도로(접합)');
console.log('UI saved',mode);const result=await page.evaluate(async({mode,key,addr})=>{const T=mode==='single'?testSingle:testMulti,ov=JSON.parse(localStorage.getItem(key)).ov;
const idx=T.buildSjIdxText('오피스텔','영등포구','2026.02.10','2026.09.21');
const ps=ArapJiphapParcels({...ov,landParcels:[{jibun:'280-1',area:100}]});
const all=T.assembleToice(ov);
window.ArapMap={create:()=>({open:items=>window.mapItems=items})};const el=document.createElement('div');el.id='mapBoxtest';document.body.appendChild(el);ArapJiphapMap.show('test',ov);
const b=ArapBldrgst.buildingFields({titles:[{dongNm:'101동',mainAtchGbCdNm:'주건축물',hoCnt:'20',hhldCnt:'0',bldNm:'검증건물 제101동'},{dongNm:'102동',mainAtchGbCdNm:'주건축물',hoCnt:'32'},{dongNm:'관리동',mainAtchGbCdNm:'부속건축물',hoCnt:'1'}],recap:{},jijigu:[]},'101동');
if(mode==='multi')for(const tpl of [T.DEFAULT_TPL_RES,T.DEFAULT_TPL_COM]){const blob=await T.generateDocxBlob(tpl,{__toice:all,Y_070:all});const entries=await T.parseZip(await blob.arrayBuffer());const x=new TextDecoder().decode(entries.find(e=>e.name==='word/document.xml').data);if(!x.includes('280-9')||!x.includes('준공업지역'))throw Error('toice missing in docx');if(new DOMParser().parseFromString(x,'application/xml').querySelector('parsererror'))throw Error('invalid docx XML');}
const map=T.buildCheongguTokenMap(ov,'하한 수수료 1,512,680\n기준 수수료 1,815,216\n상한 수수료 2,128,260','100,000','20,000','하한');
console.log('TEST building invoice');const bytes=await T.buildTokenHwpx(T.V2CHEONGGU_TPL_B64,map,T.V2CHEONGGU_BLUE2BLACK);console.log('TEST bytes',bytes.length);const entries=await T.parseZip(bytes.buffer);const xml=entries.filter(e=>/^Contents\/section\d+\.xml$/.test(e.name)).map(e=>new TextDecoder().decode(e.data)).join('');const invalid=new DOMParser().parseFromString(xml,'application/xml').querySelector('parsererror')?.textContent;
return {idx,ps,all,items:mapItems.map(x=>({loc:x.loc,poly:x.poly,label:x.label})),b,map,invalid,left:xml.includes('{{'),hasName:xml.includes('검증'),bytes:btoa(Array.from(bytes,b=>String.fromCharCode(b)).join('')),detected:T.detectSjKind('검증 오피스텔')};},{mode,key,addr});
assert.equal(result.detected,'오피스텔');assert.ok(!result.idx.err,JSON.stringify(result.idx));assert.match(result.idx.text,/서울 서남권/);assert.match(result.idx.text,/100\.58\//);assert.equal(result.ps.length,2);assert.match(result.all,/280-1[\s\S]*준공업지역[\s\S]*280-9[\s\S]*도로/);assert.deepEqual(result.items.map(x=>x.loc),['서울특별시 영등포구 당산동6가 280-1','서울특별시 영등포구 당산동6가 280-9']);assert.ok(result.items.every(x=>x.poly));assert.equal(result.b.complexScale,'2/52');assert.equal(result.b.buildingName,'검증건물');assert.ok(!result.invalid,result.invalid);assert.equal(result.left,false);assert.ok(result.hasName);if(mode==='multi'){assert.match(result.map['건명'],/304호.*704호/);assert.ok(!result.map['건명'].includes('제층'));}
fs.mkdirSync(path.join(root,'..','parity-results'),{recursive:true});fs.writeFileSync(path.join(root,'..','parity-results',mode+'.hwpx'),Buffer.from(result.bytes,'base64'));
await scope.getByText('④ 가격산출',{exact:true}).click();await scope.getByTitle('클릭해서 시점수정치 입력',{exact:true}).first().click();const officeSelect=scope.locator('select').filter({has:page.locator('option[value="오피스텔"]')});assert.equal(await officeSelect.inputValue(),'오피스텔');await scope.getByRole('button',{name:'계산',exact:true}).click();assert.match(await scope.locator('textarea').filter({visible:true}).first().inputValue(),/오피스텔/);await scope.getByRole('button',{name:'취소',exact:true}).click();await scope.getByText('② 대상물건개요',{exact:true}).click();
const q=scope.locator('input[placeholder="조회할 지번주소 또는 도로명주소를 입력하세요"]');await q.fill('이전 평가 주소');const newBtn=scope.getByRole('button',{name:/새 평가서|새평가서/});await newBtn.click();await scope.getByText('② 대상물건개요',{exact:true}).click();assert.equal(await q.inputValue(),'');assert.equal(await inputs.count(),1);
assert.deepEqual(errors,[]);console.log('PASS',mode,'parcel inputs/reload/map boundaries, officetel API series, ho-count scale, invoice XML, new report blank');await ctx.close();}}
finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});

