const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');const root=path.resolve(__dirname,'..'),out=path.join(root,'..','multi-hwpx-results');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const f=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(!f.startsWith(root)||!fs.existsSync(f)){res.statusCode=404;return res.end();}let data=fs.readFileSync(f);if(f.endsWith('s3r86w8a.html'))data=data.toString().replace("ReactDOM.createRoot(document.getElementById('root-multi'))","window.multiHelpers={applyR,getUV,parseTimeAdjDetail,numberToKoreanMoney,assembleToice,parseZip,createZipStored,buildData,generateDocxBlob,DEFAULT_TPL_RES};ReactDOM.createRoot(document.getElementById('root-multi'))");res.setHeader('Content-Type',f.endsWith('.html')?'text/html; charset=utf-8':f.endsWith('.js')?'text/javascript':'application/octet-stream');res.end(data);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL});try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.request().url().includes('arap_access.js')?r.fulfill({body:''}):r.request().url().startsWith(base)?r.continue():r.abort());await page.addInitScript(()=>{localStorage.setItem('arap-user-name','wdw');localStorage.setItem('arap-jiphap-mode','multi');});await page.goto(base+'/s3r86w8a.html');await page.waitForFunction(()=>window.multiHelpers);
for(const count of [1,3,8,20])for(const mode of count===3?['opinion','full']:['opinion']){
const r=await page.evaluate(async({count,mode})=>{const cases=Array.from({length:count===8?7:2},(_,i)=>({id:'c'+i,symbol:i+1,isShown:true,isSelected:i<2,location:'서울특별시 영등포구 당산동6가',jibun:'100-'+i,aptName:'검증 오피스텔',dong:'101',floor:'3',ho:String(301+i),exclusiveArea:30,price:150000000+i*3000000,unitPrice:5000000+i*100000,tradeDate:'2026.02.10',approvalDate:'2022.11.07',timeAdj:i?1.04:1.02,timeAdjDetail:'오피스텔\n지역 : 서울 서남권\n매매가격지수 : 2026.01 ~ 2026.08\n시점수정치 : '+(i?'104.00':'102.00')+'/100.00≒'+(i?'1.04000':'1.02000')}));
const ov={caseNo:'SYNTHETIC',client:'검증용 의뢰인',owner:'검증용 소유자',jibun:'서울특별시 영등포구 당산동6가 280-1, 280-9',buildingName:'검증건물 제102동',kind:'오피스텔',mainUse:'업무시설(오피스텔)',structure:'철근콘크리트구조',floors:'10/1',approvalDate:'2022.11.07',purpose:'일반거래(시가참고)',baseDate:'2026.09.21',surveyDate:'2026.09.20',writeDate:'2026.09.21',baseDateBasis:'의뢰일인',nearDesc:'검증역 남측 인근',toiceRaw:{'280-1':'준공업지역','280-9':'준공업지역, 도로(접합)'},units:Array.from({length:count},(_,i)=>({id:i+1,dong:i%2?'102':'101',floor:String(3+i),ho:String(301+i),area:'30',assessedArea:i===1?'15':'',commonArea:'10',landArea:'12',extFactor:'1.01',intFactor:'1.02',hoFactor:i%2?'0.97':'1.03',factorNote:'호별 비교 의견 '+(i+1)+' & 검증 <기호>',appliedSymbol:String(i%2+1)}))};
const canvas=document.createElement('canvas');canvas.width=800;canvas.height=450;const ctx=canvas.getContext('2d');ctx.fillStyle='#eaf3ff';ctx.fillRect(0,0,800,450);ctx.strokeStyle='#ef4444';ctx.lineWidth=8;ctx.strokeRect(150,100,400,250);ctx.fillStyle='#123';ctx.font='40px sans-serif';ctx.fillText('Synthetic parcel image',140,70);ov.reportImages=[{id:'map',kind:'location',caption:'검증용 위치도',width:800,height:450,dataUrl:canvas.toDataURL('image/jpeg')},{id:'photo',kind:'photo',caption:'검증용 현황사진',width:800,height:450,dataUrl:canvas.toDataURL('image/jpeg')}];
const input={ov,cases,uD:'천원',uM:'round',tD:'만원',tM:'round'};if(count===3)window.testInput=input;const result=await ArapMultiHwpx.build(input,multiHelpers,mode);const entries=await multiHelpers.parseZip(result.bytes.buffer),dec=new TextDecoder();const docs=entries.filter(e=>/^Contents\/section\d+\.xml$/.test(e.name)).map(e=>dec.decode(e.data));const d=new DOMParser().parseFromString(docs[mode==='full'?1:0],'application/xml');const tables=Array.from(d.getElementsByTagNameNS('http://www.hancom.co.kr/hwpml/2011/paragraph','tbl'));for(const t of tables){const rows=Array.from(t.children).filter(e=>e.localName==='tr'),cols=+t.getAttribute('colCnt'),grid=Array.from({length:rows.length},()=>Array(cols).fill(false));rows.forEach((row,ri)=>Array.from(row.children).filter(e=>e.localName==='tc').forEach(c=>{const addr=c.getElementsByTagNameNS('*','cellAddr')[0],span=c.getElementsByTagNameNS('*','cellSpan')[0];if(+addr.getAttribute('rowAddr')!==ri)throw Error('rowAddr');for(let y=ri;y<ri+(+span.getAttribute('rowSpan'));y++)for(let x=+addr.getAttribute('colAddr');x<(+addr.getAttribute('colAddr'))+(+span.getAttribute('colSpan'));x++){if(!grid[y]||grid[y][x]!==false)throw Error('overlap/out-of-bounds');grid[y][x]=true;}}));if(grid.some(row=>row.includes(false)))throw Error('grid hole');}for(const i of [1,2,3,4,7,8,9]){const t=tables[i];if(t.getAttribute('repeatHeader')!=='1'||t.getElementsByTagNameNS('*','pos')[0].getAttribute('treatAsChar')!=='0'||t.getElementsByTagNameNS('*','tc')[0].getAttribute('header')!=='1')throw Error('pagination/header flags');}if(+d.getElementsByTagNameNS('*','pagePr')[0].getElementsByTagNameNS('*','margin')[0].getAttribute('top')<14000)throw Error('header overlap margin');const rowCounts=tables.map(t=>Number(t.getAttribute('rowCnt')));const txt=docs.join('');return {bytes:btoa(Array.from(result.bytes,b=>String.fromCharCode(b)).join('')),rowCounts,left:txt.match(/\{\{[^}]*\}\}/g),names:entries.map(e=>e.name),amounts:result.model.rows.map(r=>r.amount),total:result.model.total,buildingName:result.model.common['건물명'],xml:docs,base:result.model.common['기준시점근거구']};},{count,mode});
assert.equal(r.left,null);assert.equal(r.rowCounts[1],6+count);assert.equal(r.rowCounts[2],1+Math.max(4,count===8?7:2));assert.equal(r.rowCounts[7],1+count*2);assert.equal(r.rowCounts[8],1+count);assert.equal(r.rowCounts[9],2+count);assert.equal(r.total,r.amounts.reduce((a,b)=>a+b,0));assert.equal(r.total,({1:162300000,3:404100000,8:1205700000,20:3133500000})[count]);assert.equal(r.base,'의뢰일인');assert.equal(r.buildingName,'검증건물');assert.ok(r.xml.join('').includes('오피스텔 가격동향조사'));assert.ok(!r.xml.join('').includes('전국주택가격동향조사'));assert.ok(!r.xml.join('').includes('상속세 및 증여세법'));if(mode==='full'){assert.ok(r.names.includes('BinData/multiImage0.jpg'));assert.ok(r.xml.join('').includes('토지이용계획'));}fs.writeFileSync(path.join(out,count+'-'+mode+'.hwpx'),Buffer.from(r.bytes,'base64'));console.log('PASS',count,mode,r.rowCounts,'total',r.total);}

const boundary=await page.evaluate(async()=>{
 const h=multiHelpers,setting={uD:'천원',uM:'round',tD:'만원',tM:'round'},unit={ho:'101',area:'30',assessedArea:'',extFactor:'1.01',intFactor:'1.02',hoFactor:'1.03',etcFactor:'0.99'},c={id:'c',symbol:5,isShown:true,isSelected:true,unitPrice:5000000,timeAdj:1.02};
 const base={ov:{...testInput.ov,units:[unit]},cases:[c],...setting};
 const calc=ArapMultiHwpx.calculateUnit(unit,c,setting,h);
 const bads=[{assessedArea:0},{assessedArea:'0'},{assessedArea:'invalid'},{assessedArea:-1},{etcFactor:0}].map(edit=>ArapMultiHwpx.model({...base,ov:{...base.ov,units:[{...unit,...edit}]}},h));
 const noAdj=ArapMultiHwpx.model({...base,cases:[{...c,timeAdj:null}]},h),noCase=ArapMultiHwpx.model({...base,cases:[]},h);
 const m=ArapMultiHwpx.model(base,h);
 const word=h.buildData(base.ov,base.cases,[],base.cases,[],{}, {},30,0,0,0,setting.uD,'반올림',setting.tD,'반올림',setting.uM,setting.tM,'주거용');
 const wordBad=h.buildData({...base.ov,units:[{...unit,assessedArea:0}]},base.cases,[],base.cases,[],{},{},30,0,0,0,setting.uD,'반올림',setting.tD,'반올림',setting.uM,setting.tM,'주거용');
 const blob=await h.generateDocxBlob(h.DEFAULT_TPL_RES,word),entries=await h.parseZip(await blob.arrayBuffer()),xml=new TextDecoder().decode(entries.find(e=>e.name==='word/document.xml').data);if(new DOMParser().parseFromString(xml,'application/xml').querySelector('parsererror'))throw Error('DOCX XML invalid');
 return {calc,amount:m.total,wordAmount:word['감정평가액'],wordUnit:word.__hoData['적용단가'][0].C_007,wordBad:wordBad['감정평가액'],wordRows:word.__hoData['거래사례'].length,wordNote:word.__hoData['가치'][0].G_026,bads:bads.map(m=>({total:m.total,area:m.rows[0].area})),noAdj:noAdj.total,noCase:noCase.total,noCaseReason:noCase.common['사례선정이유'],wordHasAmount:xml.includes('160,800,000')};
});
assert.equal(boundary.calc.rnd,5360000);assert.equal(boundary.amount,160800000);assert.equal(boundary.wordAmount,'160,800,000');assert.equal(boundary.wordUnit,'5,360,000');assert.equal(boundary.wordBad,'');assert.equal(boundary.wordRows,4);assert.match(boundary.wordNote,/0.99/);assert.ok(boundary.wordHasAmount);assert.ok(boundary.bads.every(x=>x.total===null));assert.equal(boundary.bads[0].area,0);assert.equal(boundary.noAdj,null);assert.equal(boundary.noCase,null);assert.equal(boundary.noCaseReason,'');console.log('PASS independent arithmetic / Word-HWPX parity / zero-invalid-missing guards');
// Exercise real controls and persisted case, never the user's browser profile.
await page.evaluate(()=>{localStorage.setItem('v2:appraisal-case-list',JSON.stringify([{id:'SYNTHETIC',label:'합성 검증'}]));localStorage.setItem('v2:case:SYNTHETIC',JSON.stringify({...testInput,propType:'주거용',rnd:{uD:'천원',uM:'round',tD:'만원',tM:'round'}}));});
await page.reload();const scope=page.locator('#root-multi');await scope.getByText('④ 가격산출',{exact:true}).click();
await scope.getByLabel('호별 비교 의견 1',{exact:true}).fill('직접 입력한 호별 의견');await scope.getByLabel('감정평가사',{exact:true}).fill('검증평가사');await scope.getByLabel('설비 승강기',{exact:true}).selectOption('○');
const factorTable=scope.locator('table').filter({has:page.getByRole('columnheader',{name:'기타요인',exact:true})});await factorTable.locator('tbody tr').first().locator('input').nth(3).fill('0.99');await scope.getByLabel('호별 비교 의견 1',{exact:true}).click();
await page.waitForFunction(()=>{const d=JSON.parse(localStorage.getItem('v2:case:SYNTHETIC'));return d.ov.units[0].etcFactor===0.99&&d.ov.units[0].factorNote==='직접 입력한 호별 의견'&&d.ov.appraiserName==='검증평가사';});
assert.ok((await factorTable.locator('tbody tr').first().innerText()).includes('160,800,000'));
const photo=await page.evaluate(()=>JSON.parse(localStorage.getItem('v2:case:SYNTHETIC')).ov.reportImages[0].dataUrl.split(',')[1]);await scope.locator('input[type=file][accept="image/png,image/jpeg,image/webp"]').last().setInputFiles({name:'added-photo.jpg',mimeType:'image/jpeg',buffer:Buffer.from(photo,'base64')});
await page.waitForFunction(()=>JSON.parse(localStorage.getItem('v2:case:SYNTHETIC')).ov.reportImages.length===3);
await scope.getByLabel('첨부 이미지 설명').last().fill('추가한 사진 설명');await page.waitForFunction(()=>JSON.parse(localStorage.getItem('v2:case:SYNTHETIC')).ov.reportImages[2].caption==='추가한 사진 설명');
await page.reload();await scope.getByText('④ 가격산출',{exact:true}).click();assert.equal(await scope.getByLabel('호별 비교 의견 1',{exact:true}).inputValue(),'직접 입력한 호별 의견');assert.equal(await scope.getByLabel('감정평가사',{exact:true}).inputValue(),'검증평가사');assert.equal(await scope.getByLabel('설비 승강기',{exact:true}).inputValue(),'○');assert.equal(await scope.getByLabel('첨부 이미지 설명').last().inputValue(),'추가한 사진 설명');assert.equal(await factorTable.locator('tbody tr').first().locator('input').nth(3).inputValue(),'0.99');
const downloadBtn=scope.getByRole('button',{name:'1. 감정평가서 (전체 한글)',exact:true});await page.waitForFunction(()=>Array.from(document.querySelectorAll('#root-multi button')).some(b=>b.textContent==='1. 감정평가서 (전체 한글)'&&!b.disabled));const dlPromise=page.waitForEvent('download');await downloadBtn.click();const dl=await dlPromise;assert.match(dl.suggestedFilename(),/감정평가서.*hwpx$/);await dl.saveAs(path.join(out,'ui-full.hwpx'));console.log('PASS real UI calculations / factor-note-signature-photo save-reload / full HWPX download');
await scope.screenshot({path:path.join(out,'multi-ui.png')});await scope.getByText('② 대상물건개요',{exact:true}).click();const unitTable=scope.locator('table').filter({has:page.getByRole('columnheader',{name:'사정면적',exact:true})});await unitTable.locator('tbody tr').first().locator('input').nth(7).fill('0');await scope.getByText('④ 가격산출',{exact:true}).click();assert.equal(await scope.getByText('미완료',{exact:true}).count(),1);await page.waitForFunction(()=>JSON.parse(localStorage.getItem('v2:case:SYNTHETIC')).ov.units[0].assessedArea==='0');await page.reload();await scope.getByText('④ 가격산출',{exact:true}).click();assert.equal(await scope.getByText('미완료',{exact:true}).count(),1);console.log('PASS assessed zero UI/reload leaves total incomplete');
assert.deepEqual(errors,[]);
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
