const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');const root=path.resolve(__dirname,'..'),out=path.join(root,'..','multi-hwpx-results');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const f=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(!f.startsWith(root)||!fs.existsSync(f)){res.statusCode=404;return res.end();}let data=fs.readFileSync(f);if(f.endsWith('s3r86w8a.html'))data=data.toString().replace("ReactDOM.createRoot(document.getElementById('root-multi'))","window.multiHelpers={applyR,getUV,parseTimeAdjDetail,numberToKoreanMoney,assembleToice,parseZip,createZipStored,buildData,generateDocxBlob,DEFAULT_TPL_RES};ReactDOM.createRoot(document.getElementById('root-multi'))");res.setHeader('Content-Type',f.endsWith('.html')?'text/html; charset=utf-8':f.endsWith('.js')?'text/javascript':'application/octet-stream');res.end(data);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL});try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.request().url().includes('arap_access.js')?r.fulfill({body:''}):r.request().url().startsWith(base)?r.continue():r.abort());await page.addInitScript(()=>{localStorage.setItem('arap-user-name','wdw');localStorage.setItem('arap-jiphap-mode','multi');});await page.goto(base+'/s3r86w8a.html');await page.waitForFunction(()=>window.multiHelpers);
for(const count of [1,3,8,20])for(const mode of count===3?['opinion','full']:['opinion']){
const r=await page.evaluate(async({count,mode})=>{const cases=Array.from({length:count===8?7:2},(_,i)=>({id:'c'+i,symbol:i+1,isShown:true,isSelected:i<2,location:'서울특별시 영등포구 당산동6가',jibun:'100-'+i,aptName:'검증 오피스텔',dong:'101',floor:'3',ho:String(301+i),exclusiveArea:30,price:150000000+i*3000000,unitPrice:5000000+i*100000,tradeDate:'2026.02.10',approvalDate:'2022.11.07',timeAdj:i?1.04:1.02,timeAdjDetail:'오피스텔\n지역 : 서울 서남권\n매매가격지수 : 2026.01 ~ 2026.08\n시점수정치 : '+(i?'104.00':'102.00')+'/100.00≒'+(i?'1.04000':'1.02000')}));
const ov={caseNo:'SYNTHETIC',client:'검증용 의뢰인',owner:'검증용 소유자',jibun:'서울특별시 영등포구 당산동6가 280-1, 280-9',buildingName:'검증건물 제102동',kind:'오피스텔',mainUse:'업무시설(오피스텔)',structure:'철근콘크리트구조',floors:'10/1',approvalDate:'2022.11.07',purpose:'일반거래(시가참고)',baseDate:'2026.09.21',surveyDate:'2026.09.20',writeDate:'2026.09.21',baseDateBasis:'의뢰일인',nearDesc:'검증역 남측 인근',toiceRaw:{'280-1':'준공업지역','280-9':'준공업지역, 도로(접합)'},units:Array.from({length:count},(_,i)=>({id:i+1,dong:i%2?'102':'101',floor:String(3+i),ho:String(301+i),area:'30',assessedArea:i===1?'15':'',commonArea:'10',landArea:'12',extFactor:'1.01',intFactor:'1.02',hoFactor:i%2?'0.97':'1.03',factorNote:count===1?'':'호별 비교 의견 '+(i+1)+' & 검증 <기호>',appliedSymbol:String(i%2+1)}))};
const canvas=document.createElement('canvas');canvas.width=800;canvas.height=450;const ctx=canvas.getContext('2d');ctx.fillStyle='#eaf3ff';ctx.fillRect(0,0,800,450);ctx.strokeStyle='#ef4444';ctx.lineWidth=8;ctx.strokeRect(150,100,400,250);ctx.fillStyle='#123';ctx.font='40px sans-serif';ctx.fillText('Synthetic parcel image',140,70);ov.reportImages=[{id:'map',kind:'location',caption:'검증용 위치도',width:800,height:450,dataUrl:canvas.toDataURL('image/jpeg')},{id:'photo',kind:'photo',caption:'검증용 현황사진',width:800,height:450,dataUrl:canvas.toDataURL('image/jpeg')}];
const input={ov,cases,uD:'천원',uM:'round',tD:'만원',tM:'round'};if(count===3)window.testInput=input;const result=await ArapMultiHwpx.build(input,multiHelpers,mode);const entries=await multiHelpers.parseZip(result.bytes.buffer),dec=new TextDecoder();const docs=entries.filter(e=>/^Contents\/section\d+\.xml$/.test(e.name)).map(e=>dec.decode(e.data));const d=new DOMParser().parseFromString(docs[mode==='full'?1:0],'application/xml');const tables=Array.from(d.getElementsByTagNameNS('http://www.hancom.co.kr/hwpml/2011/paragraph','tbl'));for(const t of tables){const rows=Array.from(t.children).filter(e=>e.localName==='tr'),cols=+t.getAttribute('colCnt'),grid=Array.from({length:rows.length},()=>Array(cols).fill(false));rows.forEach((row,ri)=>Array.from(row.children).filter(e=>e.localName==='tc').forEach(c=>{const addr=c.getElementsByTagNameNS('*','cellAddr')[0],span=c.getElementsByTagNameNS('*','cellSpan')[0];if(+addr.getAttribute('rowAddr')!==ri)throw Error('rowAddr');for(let y=ri;y<ri+(+span.getAttribute('rowSpan'));y++)for(let x=+addr.getAttribute('colAddr');x<(+addr.getAttribute('colAddr'))+(+span.getAttribute('colSpan'));x++){if(!grid[y]||grid[y][x]!==false)throw Error('overlap/out-of-bounds');grid[y][x]=true;}}));if(grid.some(row=>row.includes(false)))throw Error('grid hole');}for(const i of [1,2,3,4,7,8,9]){const t=tables[i];if(t.getAttribute('repeatHeader')!=='1'||t.getElementsByTagNameNS('*','pos')[0].getAttribute('treatAsChar')!=='0'||t.getElementsByTagNameNS('*','tc')[0].getAttribute('header')!=='1')throw Error('pagination/header flags');}const rowCounts=tables.map(t=>Number(t.getAttribute('rowCnt')));const txt=docs.join('');return {bytes:btoa(Array.from(result.bytes,b=>String.fromCharCode(b)).join('')),rowCounts,left:txt.match(/\{\{[^}]*\}\}/g),names:entries.map(e=>e.name),amounts:result.model.rows.map(r=>r.amount),total:result.model.total,buildingName:result.model.common['건물명'],xml:docs,base:result.model.common['기준시점근거구']};},{count,mode});
assert.equal(r.left,null);assert.equal(r.rowCounts[1],6+count);assert.equal(r.rowCounts[2],1+Math.max(4,count===8?7:2));assert.equal(r.rowCounts[7],1+count*2);assert.equal(r.rowCounts[8],1+count);assert.equal(r.rowCounts[9],2+count);assert.equal(r.total,r.amounts.reduce((a,b)=>a+b,0));assert.equal(r.total,({1:162300000,3:404100000,8:1205700000,20:3133500000})[count]);assert.equal(r.base,'의뢰일인');assert.equal(r.buildingName,'검증건물');assert.ok(r.xml.join('').includes('오피스텔 가격동향조사'));assert.ok(!r.xml.join('').includes('전국주택가격동향조사'));assert.ok(r.xml.join('').replace(/<[^>]+>/g,'').replace(/\s/g,'').includes('「상속세및증여세법」상'));if(count===1)assert.ok(r.xml.join('').includes('- 외부요인:'));if(mode==='full'){assert.ok(!r.names.includes('BinData/multiImage0.jpg'));assert.equal(r.rowCounts.length,10);assert.ok(!r.xml.join('').includes('감정평가명세표')); }fs.writeFileSync(path.join(out,count+'-'+mode+'.hwpx'),Buffer.from(r.bytes,'base64'));console.log('PASS',count,mode,r.rowCounts,'total',r.total);}

for(const count of [1,3,8,20]){
 const result=await page.evaluate(async count=>{
  const ov={...testInput.ov,floorDetail:'1층 100.00\n2층 100.00',units:Array.from({length:count},(_,i)=>({...testInput.ov.units[i%3],id:i+1,ho:String(301+i)}))};
  const input={...testInput,ov},out={};
  for(const kind of ['yohang','myeongse']){const r=await ArapMultiDocuments[kind](input,multiHelpers);const es=await multiHelpers.parseZip(r.bytes.buffer);for(const e of es.filter(e=>/\.xml$|\.rels$/.test(e.name))){if(new DOMParser().parseFromString(new TextDecoder().decode(e.data),'application/xml').querySelector('parsererror'))throw Error('Invalid XML: '+e.name);}
   out[kind]=btoa(Array.from(r.bytes,b=>String.fromCharCode(b)).join(''));
   if(kind==='myeongse'){for(const e of es.filter(e=>/unit\d+\/worksheets\/sheet1.xml$/.test(e.name))){const d=new DOMParser().parseFromString(new TextDecoder().decode(e.data),'application/xml');const val=ref=>d.querySelector('c[r="'+ref+'"] v')?.textContent||'';if(val('I34')!==val('I48'))throw Error('Stale printed total cache');}}
   if(kind==='yohang'){const d=new DOMParser().parseFromString(new TextDecoder().decode(es.find(e=>e.name==='Contents/section0.xml').data),'application/xml');const txt=d.documentElement.textContent;if(txt.includes('{{'))throw Error('Unresolved token');for(let i=0;i<count;i++)if(!txt.includes('제'+(301+i)+'호'))throw Error('Missing unit');}
  }return out;
 },count);
 for(const kind of ['yohang','myeongse'])fs.writeFileSync(path.join(out,count+'-'+kind+(kind==='yohang'?'.hwpx':'.xlsx')),Buffer.from(result[kind],'base64'));
 console.log('PASS separate documents',count);
}
const incomplete=await page.evaluate(async()=>{const result=await ArapMultiDocuments.myeongse({...testInput,ov:{...testInput.ov,units:[{...testInput.ov.units[0],assessedArea:0}]},cases:[]},multiHelpers);return btoa(Array.from(result.bytes,b=>String.fromCharCode(b)).join(''));});fs.writeFileSync(path.join(out,'incomplete.xlsx'),Buffer.from(incomplete,'base64'));

const purposeTexts=await page.evaluate(async()=>{
 const out=[];
 for(const evalCategory of ['', '상속', '증여']){
  const result=await ArapMultiHwpx.build({...testInput,ov:{...testInput.ov,evalCategory}},multiHelpers,'opinion');
  const entries=await multiHelpers.parseZip(result.bytes.buffer);
  const doc=new DOMParser().parseFromString(new TextDecoder().decode(entries.find(e=>e.name==='Contents/section0.xml').data),'application/xml');
  const header=new DOMParser().parseFromString(new TextDecoder().decode(entries.find(e=>e.name==='Contents/header.xml').data),'application/xml');
  const chars=Array.from(header.getElementsByTagNameNS('*','charPr'));
  const paragraphs=Array.from(doc.getElementsByTagNameNS('*','p'));
  const content=p=>Array.from(p.children).filter(e=>e.localName==='run').flatMap(r=>Array.from(r.children).filter(e=>e.localName==='t')).map(t=>t.textContent).join('');
  const survey=paragraphs.find(p=>content(p).includes('실지조사를 하여'));
  const reference=paragraphs.find(p=>content(p).includes('기준시점은'));
  const styles=p=>Array.from(p.children).filter(r=>r.localName==='run'&&Array.from(r.children).some(e=>e.localName==='t'&&e.textContent.trim())).map(r=>chars.find(c=>c.getAttribute('id')===r.getAttribute('charPrIDRef')));
  const expected=styles(reference)[0];
  for(const style of styles(survey)){
   if(style.getAttribute('height')!==expected.getAttribute('height')||style.getElementsByTagNameNS('*','fontRef')[0].outerHTML!==expected.getElementsByTagNameNS('*','fontRef')[0].outerHTML)throw Error('Survey paragraph font differs from body');
  }
  out.push(Array.from(doc.getElementsByTagNameNS('*','t')).map(t=>t.textContent).join('').replace(/\s/g,''));
 }
 return out;
});
for(const [i,category] of ['', '상속', '증여'].entries())assert.ok(purposeTexts[i].includes('「상속세및증여세법」상'+category+'재산에대한일반거래(시가참고)목적의감정평가임.'));
console.log('PASS template purpose wording retained with blank/inheritance/gift category');
const boundary=await page.evaluate(async()=>{
 const h=multiHelpers,setting={uD:'천원',uM:'round',tD:'만원',tM:'round'},unit={ho:'101',area:'30',assessedArea:'',extFactor:'1.01',intFactor:'1.02',hoFactor:'1.03',etcFactor:'0.99'},c={id:'c',symbol:5,isShown:true,isSelected:true,unitPrice:5000000,timeAdj:1.02};
 const base={ov:{...testInput.ov,units:[unit]},cases:[c],...setting};
 const calc=ArapMultiHwpx.calculateUnit(unit,c,setting,h);
 const bads=[{assessedArea:0},{assessedArea:'0'},{assessedArea:'invalid'},{assessedArea:-1},{etcFactor:0}].map(edit=>ArapMultiHwpx.model({...base,ov:{...base.ov,units:[{...unit,...edit}]}},h));
 const noAdj=ArapMultiHwpx.model({...base,cases:[{...c,timeAdj:null}]},h),noCase=ArapMultiHwpx.model({...base,cases:[]},h);
 const m=ArapMultiHwpx.model(base,h);
 const word=h.buildData(base.ov,base.cases,[],base.cases,[],{}, {},30,0,0,0,setting.uD,'반올림',setting.tD,'반올림',setting.uM,setting.tM,'주거용');
 const wordBad=h.buildData({...base.ov,units:[{...unit,assessedArea:0}]},base.cases,[],base.cases,[],{},{},30,0,0,0,setting.uD,'반올림',setting.tD,'반올림',setting.uM,setting.tM,'주거용');
 const blob=await h.generateDocxBlob(h.DEFAULT_TPL_RES,word),entries=await h.parseZip(await blob.arrayBuffer()),xml=new TextDecoder().decode(entries.find(e=>e.name==='word/document.xml').data);if(new DOMParser().parseFromString(xml,'application/xml').querySelector('parsererror'))throw Error('DOCX XML invalid');
 return {calc,amount:m.total,defaultNote:m.rows[0].values['개별요인_의견'],wordAmount:word['감정평가액'],wordUnit:word.__hoData['적용단가'][0].C_007,wordBad:wordBad['감정평가액'],wordRows:word.__hoData['거래사례'].length,wordNote:word.__hoData['가치'][0].G_026,bads:bads.map(m=>({total:m.total,area:m.rows[0].area})),noAdj:noAdj.total,noCase:noCase.total,noCaseReason:noCase.common['사례선정이유'],wordHasAmount:xml.includes('160,800,000')};
});
assert.equal(boundary.calc.rnd,5360000);assert.equal(boundary.amount,160800000);assert.equal(boundary.defaultNote,'- 외부요인:\n- 내부요인:\n- 호별요인:\n- 기타요인:');assert.equal(boundary.wordAmount,'160,800,000');assert.equal(boundary.wordUnit,'5,360,000');assert.equal(boundary.wordBad,'');assert.equal(boundary.wordRows,4);assert.match(boundary.wordNote,/0.99/);assert.ok(boundary.wordHasAmount);assert.ok(boundary.bads.every(x=>x.total===null));assert.equal(boundary.bads[0].area,0);assert.equal(boundary.noAdj,null);assert.equal(boundary.noCase,null);assert.equal(boundary.noCaseReason,'');console.log('PASS independent arithmetic / Word-HWPX parity / default factor note / zero-invalid-missing guards');
// Exercise real controls and persisted case, never the user's browser profile.
await page.evaluate(()=>{localStorage.setItem('v2:appraisal-case-list',JSON.stringify([{id:'SYNTHETIC',label:'합성 검증'}]));const ov={...testInput.ov,units:testInput.ov.units.map((u,i)=>i?u:{...u,factorNote:''})};localStorage.setItem('v2:case:SYNTHETIC',JSON.stringify({...testInput,ov,propType:'주거용',rnd:{uD:'천원',uM:'round',tD:'만원',tM:'round'}}));});
await page.reload();const scope=page.locator('#root-multi');await scope.getByText('① 접수개요',{exact:true}).click();assert.equal(await scope.getByText('탁상가격 (호별)',{exact:true}).count(),0);await scope.getByText('④ 가격산출',{exact:true}).click();assert.equal(await scope.getByText('한글 감정평가서 출력 정보',{exact:true}).count(),0);
assert.equal(await scope.getByLabel('호별 비교 의견 1',{exact:true}).inputValue(),'- 외부요인:\n- 내부요인:\n- 호별요인:\n- 기타요인:');await scope.getByLabel('호별 비교 의견 1',{exact:true}).fill('직접 입력한 호별 의견');
const factorTable=scope.locator('table').filter({has:page.getByRole('columnheader',{name:'기타요인',exact:true})});await factorTable.locator('tbody tr').first().locator('input').nth(3).fill('0.99');await scope.getByLabel('호별 비교 의견 1',{exact:true}).click();
await page.waitForFunction(()=>{const d=JSON.parse(localStorage.getItem('v2:case:SYNTHETIC'));return d.ov.units[0].etcFactor===0.99&&d.ov.units[0].factorNote==='직접 입력한 호별 의견';});
assert.ok((await factorTable.locator('tbody tr').first().innerText()).includes('160,800,000'));
await page.reload();await scope.getByText('④ 가격산출',{exact:true}).click();assert.equal(await scope.getByLabel('호별 비교 의견 1',{exact:true}).inputValue(),'직접 입력한 호별 의견');assert.equal(await factorTable.locator('tbody tr').first().locator('input').nth(3).inputValue(),'0.99');
const downloadBtn=scope.getByRole('button',{name:'표지/괄감/의견서',exact:true});await page.waitForFunction(()=>Array.from(document.querySelectorAll('#root-multi button')).some(b=>b.textContent==='표지/괄감/의견서'&&!b.disabled));const dlPromise=page.waitForEvent('download');await downloadBtn.click();const dl=await dlPromise;assert.match(dl.suggestedFilename(),/감정평가서.*hwpx$/);await dl.saveAs(path.join(out,'ui-full.hwpx'));console.log('PASS real UI calculations / factor-note save-reload / full HWPX download');
for(const [name,ext] of [['요항표','hwpx'],['명세표(excel)','xlsx']]){const promise=page.waitForEvent('download');await scope.getByRole('button',{name,exact:true}).click();const download=await promise;assert.ok(download.suggestedFilename().endsWith('.'+ext));await download.saveAs(path.join(out,'ui-'+(ext==='xlsx'?'myeongse.xlsx':'yohang.hwpx')));}console.log('PASS three download buttons');
await scope.screenshot({path:path.join(out,'multi-ui.png')});await scope.getByText('② 대상물건개요',{exact:true}).click();const unitTable=scope.locator('table').filter({has:page.getByRole('columnheader',{name:'사정면적',exact:true})});await scope.getByLabel('탁상단가 가',{exact:true}).fill('6000000');await page.waitForFunction(()=>{const u=JSON.parse(localStorage.getItem('v2:case:SYNTHETIC')).ov.units[0];return u.deskPrice==='180000000'&&u.deskPriceBasis==='unit';});await unitTable.locator('tbody tr').first().locator('input').nth(7).fill('15');await page.waitForFunction(()=>{const u=JSON.parse(localStorage.getItem('v2:case:SYNTHETIC')).ov.units[0];return u.deskPrice==='90000000'&&u.deskUnitPrice==='6000000';});await page.reload();await scope.getByText('② 대상물건개요',{exact:true}).click();assert.equal(await scope.getByLabel('탁상단가 가',{exact:true}).inputValue(),'6,000,000');await unitTable.locator('tbody tr').first().locator('input').nth(7).fill('0');await scope.getByText('④ 가격산출',{exact:true}).click();assert.equal(await scope.getByText('미완료',{exact:true}).count(),1);await page.waitForFunction(()=>JSON.parse(localStorage.getItem('v2:case:SYNTHETIC')).ov.units[0].assessedArea==='0');await page.reload();await scope.getByText('④ 가격산출',{exact:true}).click();assert.equal(await scope.getByText('미완료',{exact:true}).count(),1);console.log('PASS direct desk unit / basis persistence / assessed zero incomplete guard');
// Each unit can choose a case before any global checkboxes are selected.
await page.evaluate(()=>{const saved=JSON.parse(localStorage.getItem('v2:case:SYNTHETIC'));const input={...saved,cases:saved.cases.map(c=>({...c,isSelected:false})),ov:{...saved.ov,units:saved.ov.units.map(u=>{const next={...u,assessedArea:'30'};delete next.appliedSymbol;delete next.appliedCaseId;return next;})},propType:'주거용',rnd:{uD:'천원',uM:'round',tD:'만원',tM:'round'}};localStorage.setItem('v2:case:SYNTHETIC',JSON.stringify(input));});
await page.reload();await scope.getByText('④ 가격산출',{exact:true}).click();
assert.equal(await scope.getByLabel('적용 사례 가',{exact:true}).inputValue(),'');
await scope.getByLabel('적용 사례 가',{exact:true}).selectOption('c1');
await scope.getByLabel('적용 사례 나',{exact:true}).selectOption('c0');
await scope.getByLabel('적용 사례 다',{exact:true}).selectOption('c1');
await page.waitForFunction(()=>JSON.parse(localStorage.getItem('v2:case:SYNTHETIC')).ov.units.every((u,i)=>u.appliedCaseId===(i===1?'c0':'c1')));
await page.reload();await scope.getByText('④ 가격산출',{exact:true}).click();
for(const [symbol,id] of [['가','c1'],['나','c0'],['다','c1']])assert.equal(await scope.getByLabel('적용 사례 '+symbol,{exact:true}).inputValue(),id);
const assigned=await page.evaluate(async()=>{
 const input=JSON.parse(localStorage.getItem('v2:case:SYNTHETIC')),h=multiHelpers;
 const result=await ArapMultiHwpx.build(input,h,'opinion');
 const entries=await h.parseZip(result.bytes.buffer);
 const doc=new DOMParser().parseFromString(new TextDecoder().decode(entries.find(e=>e.name==='Contents/section0.xml').data),'application/xml');
 const factor=Array.from(doc.getElementsByTagNameNS('*','tbl'))[7];
 const texts=Array.from(factor.children).filter(e=>e.localName==='tr').filter((r,i)=>i%2===1).map(r=>r.textContent);
 const word=h.buildData(input.ov,input.cases,[],input.cases.filter(c=>c.isSelected),[],{},{},30,0,0,0,input.uD,'반올림',input.tD,'반올림',input.uM,input.tM,'주거용');
 const reindexed=input.cases.map(c=>({...c,symbol:99-c.symbol}));
 const missing=ArapMultiHwpx.model({...input,cases:input.cases.filter(c=>c.id!=='c1')},h);
 return {ids:result.model.rows.map(r=>r.c.id),texts,wordSymbols:[word.Y_265,word.Y_268],reindexed:input.ov.units.map(u=>ArapMultiHwpx.resolveCase(u,reindexed)?.id),missing:missing.rows.map(r=>r.amount),total:missing.total};
});
assert.deepEqual(assigned.ids,['c1','c0','c1']);assert.deepEqual(assigned.reindexed,assigned.ids);
assert.ok(assigned.texts[0].includes('#2'));assert.ok(assigned.texts[1].includes('#1'));assert.ok(assigned.texts[2].includes('#2'));
assert.deepEqual(assigned.wordSymbols,['#2','#1']);assert.equal(assigned.missing[0],null);assert.equal(assigned.missing[2],null);assert.equal(assigned.total,null);
console.log('PASS independent unit case selection / reload / HWPX-Word mapping / stable IDs / removed-case guard');
assert.deepEqual(errors,[]);
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
